### ISSUE TITLE
Renaming team contacts property

### ISSUE THREAD

**Issue by jean-gui** [darobin/w3capi#1]
Hi,

On https://api-test.w3.org/groups/xxx/teamcontacts?embed=true, We are going to rename the property `teamcontacts` to `team_contacts`, for consistency with https://api-test.w3.org/groups/xxx.
Does that require a change here or in ash-nazg?

**Comment by darobin** [comment]
Are you also changing the URL name, i.e. https://api-test.w3.org/groups/xxx/teamcontacts -> https://api-test.w3.org/groups/xxx/team_contacts ?

**Comment by jean-gui** [comment]
No, only the property name

**Comment by darobin** [comment]
In that case I don't need a change, thanks.
